### ISSUE TITLE
Autofill problem with MS Edge

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#243] opened 2018-09-16 11:42 UTC
First reported here: https://wordpress.org/support/topic/autocomplete-still-possible-with-edge/

> I could reproduce this “bug” with MS Edge:
> I added the form-information to the MS Edge settings and then I posted a comment, using the autofill function of Edge for the email address and first name.

> The comment was marked as spam by the Antispam Bee (honeypot), but instead of the original  comment, it showed my address when I checked the spam-comment overview.

> We use up-to-date versions of WP as well as the latest version of the Antispam Bee (where autocomplete=”nope” is implemented).

**Comment by dionysous** [comment] 2018-09-20 08:30
In general, when you use the attribute `autocomplete` on inputs, you can use the value "on" or "off". I am wondering why "nope" is used in Antispam-Bee, it has no effect. Maybe chaning this to "off" will fix this problem.

**Comment by websupporter** [comment] 2018-09-20 08:31
Hi @dionysous, for context see here https://github.com/pluginkollektiv/antispam-bee/issues/142

**Comment by florianbrinkmann** [comment] 2018-09-20 08:36
I’ll look into this.

**Comment by florianbrinkmann** [comment] 2018-09-20 09:46
I cannot reproduce it with the `master` version of Antispam Bee and Microsoft EdgeHTML 18.17730 / Microsoft Edge 44.17730.1000.0.

I added autofill data for name, email, address and used the feature to autofill the name and email field before submitting a comment. The comment text is saved correctly for me.

**Comment by Zodiac1978** [comment] 2018-09-20 10:03
@florianbrinkmann According to the original forum post linked above the Edge version is `Edge/17.17134`

**Comment by 2ndkauboy** [comment] 2018-09-20 10:30
I could not reproduce the bug: https://wordpress.org/support/topic/autocomplete-still-possible-with-edge/#post-10706480 (with master or tag 2.9.0).

**Comment by websupporter** [comment] 2018-09-20 12:40
I tried it some days ago as well using https://www.browserstack.com/ and couldn't reproduce it.

**Comment by Zodiac1978** [comment] 2018-09-23 11:47
New input:
https://wordpress.org/support/topic/autocomplete-still-possible-with-edge/#post-10707129

```
$comment_args = array(
        'comment_field'           => '<label for="comment">a</label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea>' // this Works! Wohoo!
        //'comment_field'         => '<label for="comment">&nbsp;</label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea>' // Doesn't work
        //'comment_field'         => '<textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea>', // Doesn't work
        //'comment_field'         => '<label for="comment"></label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea>' // Doesn't work
        //'comment_field' 		  => '<p class="comment-form-comment"><label for="comment">Custom Kommentarfeld</label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea></p>', // Default WP-Field as in https://codex.wordpress.org/Function_Reference/comment_form - works, but not what I need
    );

    comment_form($comment_args);
```

**Comment by florianbrinkmann** [comment] 2018-09-25 07:55
I’ll try to reproduce it.

**Comment by florianbrinkmann** [comment] 2018-09-25 08:06
I can reproduce it. Will look how to fix that.

**Comment by florianbrinkmann** [comment] 2018-09-25 08:46
Okay, I don’t understand it but the thing is:

As soon as the label is not there or empty, Edge filles the address in the comment field. If that field already contains a comment, it fills the address in the hidden field. If the label has a character but is hidden via `display: none`, it works correctly, so my not-so-pretty-but-working proposal for a fix would be:

1. Check if there is a label element for the comment textarea.
2. If not or if it is empty, add a pseudo label and hide it via CSS.

Edge seems to ignore the autocomplete thing (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9847360/#comment-4), so I don’t know how that could be fixed otherwise.

**Comment by websupporter** [comment] 2018-09-25 08:57
I am not totally opposed against it, but want to stress out, I think we solve an issue, which is an issue of Edge and they should solve it. Its terrible how browser vendors think, they can handle this autocomplete issue as they like.

So, an alternative approach might be an answer to the support request.
> Now I want to proove that this is not a problem caused by us (WP or Plugins) but by the browser.
> My google research wasn’t that successful regarding autofill-bugs (with Edge) – so hopefully someone of you can help me out?

Something along those lines:
>we think as well, its a browser problem (see the discussion here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9847360/) and should be fixed in Edge. A workaround could be to add an invisible label, as suggested above.

I am not really decided on this way, but would like to bring it to the table. The "nope" solution in #142 leans towards: We should fix it in ASB. If we follow this path, I think the solution by @florianbrinkmann is suitable. It could be the same styles like we use for the hidden field.

**Comment by florianbrinkmann** [comment] 2018-09-25 09:37
> So, an alternative approach might be an answer to the support request.

Yes, good point, we could add a small code snippet that works as a workaround – maybe that could be linked from the FAQ if that issue appears again. Her last reply reads like she wants to add a label, so that should be fixed for her.

Additionally we could try to create an issue in Microsoft’s bug tracker, because that is not the exact same issue – for that we would need a small site that contains the bug reproducable.

**Comment by Zodiac1978** [comment] 2019-06-03 12:22
What is the status of this issue and the corresponding support thread? Can I close it? Do we have added this snippet in the Wiki/FAQ? Ping @florianbrinkmann @websupporter

**Comment by florianbrinkmann** [comment] 2019-06-05 08:17
Oops, totally forgot the issue, sorry. I will check if that is a problem in the current version of Edge, and if so, write an answer in the support thread, that it is a browser problem and how to fix it with a hidden label.

**Comment by Zodiac1978** [comment] 2019-06-05 08:33
Thank you @florianbrinkmann !

**Comment by florianbrinkmann** [comment] 2019-11-11 09:07
So, I tried to reproduce that again with the `master` version of Antispam Bee and the Microsoft Edge 44.19018.1.0./Microsoft EdgeHTML 18.19018. I will add a reply to the support forum.

**Closed** 2019-11-11 09:21 UTC
Labels: Hacktoberfest, bug
