### ISSUE TITLE
Compatibility between Antispam Bee and WPML / Mail from WPML

### ISSUE THREAD

**Issue by staude** [pluginkollektiv/antispam-bee#17] opened 2015-09-17 09:29 UTC
I received this Mail from WPML 

---

Dear Frank,

My name is Helena from WPML.  We have received a request in our support forum to check on the compatibility of Antispam Bee with WPML  which you may find here:
 https://wpml.org/de/forums/topic/kommentare-schreiben-nicht-moeglich-bei-fremdsprache/

Description by the assigned supporter:

 When WPML and Antispam Bee are activated the comments in 2nd language are not working :

 https://d2salfytceyqoe.cloudfront.net/wp-content/uploads/2015/09/704843-Bildschirmfoto_2015_09_14_um_20.48.24.png
 https://d2salfytceyqoe.cloudfront.net/wp-content/uploads/2015/09/704843-Bildschirmfoto_2015_09_14_um_20.48.33.png

In order to get  Antispam Bee fully compatible with WPML,   we would like to invite you  to join our  GoGlobal  program which is specially designed for developers.

http://wpml.org/documentation/theme-compatibility/go-global-program/

Simply complete the details and then send directly to me your latest version by mail.    We will set up a test site with your theme/plugin installed where we can work on the issues together, test it and give you a detailed report of the results.

After the process is complete, we will announce it to our users and add Antispam Bee  to our compatibility page.

You can see the successful list here

http://wpml.org/documentation/theme-compatibility/

http://wpml.org/documentation/plugins-compatibility/

Looking forward to hearing from you,

Helena Petridou
WPML administrative assistant
OnTheGoSystems
www.onthegosystems.com
The makers of WPML, Toolset and ICanLocalize

**Comment by swissspidy** [comment] 2015-09-17 09:38
So Antispam Bee doesn't work correctly on multilingual sites, no matter what plugin is used? Or is it just restricted to WPML?

The "Allow comments only in certain language" setting isn't available at the moment, so that can't be the culprit.

**Comment by staude** [comment] 2015-09-17 09:51
I have sent Helena the URL to this ticket and hope that expresses itself. even I can not say anything, except that I got the mail.

**Comment by swissspidy** [comment] 2015-10-08 09:29
Closing this as per our recent discussion on Slack.

**Comment by nadalsol** [comment] 2016-09-15 12:50
Sorry to bother you @swissspidy but has this issue been solved?

I'm having this exact problem on my site:
https://wordpress.org/support/topic/problem-with-multi-language-site/

WordPress v 4.6.1
Anti Spam Bee v 2.6.9

Thanks for your time

**Comment by swissspidy** [comment] 2016-09-15 13:10
Can we please settle on using either GitHub or the support forums for discussing this? 🙂

Have you already reached out to WPML to see if they can help?

Regarding compatibility, it's always tough to say who is responsible for making it work. Based on my experience WPML is badly programmed and other multilingual plugins like Polylang are working absolutely fine with Antispam Bee.

We're not participating in WPML's GoGlobal program, which this issue is about, as none of us uses WPML and there was only 1 question about WPML support so far — yours is the second one. Thus, this has a rather low priority for us.

**Comment by nadalsol** [comment] 2016-09-19 10:44
Hi @swissspidy 

No, I've not reached WPML yet because following this conversation –and [other ones about the same topic](https://wordpress.org/support/topic/problem-with-multi-language-site/))– it's still not clear to me if the issue is from WPML or Antispam Bee.

Even agreeing with some of your points about WPML the reality is that I'm using it in a big organisation/site and it's difficult to get rid of such a "core" plugin like this one.

I will try to contact WPML support soon, looking for a solution...

I appreciate your response.

**Comment by nadalsol** [comment] 2016-09-19 11:02
Opened a ticket to WPML here:
https://wpml.org/forums/topic/compatibility-between-antispam-bee-and-wpml/

Cheers

**Comment by Zodiac1978** [comment] 2016-11-22 22:28
Just filled out the application for the GoGlobal Program. Maybe this helps them finding the problem.

**Comment by Zodiac1978** [comment] 2017-01-27 10:00
Today I got an answer from WPML. They are testing now and next week we will get the results of this testing. I'll keep you updated.

**Comment by dgwatkins** [comment] 2017-01-27 15:42
The problem in the generation of the secret (it uses home which has language information attached).
`		self::$_secret = substr(md5(get_bloginfo('url')), 0, 5). '-comment';`

The solution is as easy as use the siteurl instead:
`		self::$_secret = substr(md5(get_bloginfo('wpurl')), 0, 5). '-comment';`

Let me send a pull request

**Comment by timse201** [comment] 2017-01-27 15:46
could be that this will be fixed with #56

**Comment by Zodiac1978** [comment] 2017-01-27 15:47
Hey @dgwatkins ! Thank you for your help. No need for a pull request as this line is changing in the next update with #56

**Comment by dgwatkins** [comment] 2017-01-27 15:49
Yes, #56 handles the issue perfectly.
Thank you too!

**Comment by timse201** [comment] 2017-02-02 12:53
Should be fixed now

**Comment by schlessera** [comment] 2017-02-02 12:55
Not exactly, that PR is still not merged. I'll discuss with @websupporter to get it in during this week.

**Comment by timse201** [comment] 2017-02-02 15:53
Ups right

**Comment by websupporter** [comment] 2017-02-04 15:59
Fixed by #56

**Closed by websupporter** 2017-02-04 15:59 UTC
Labels: bug
