### ISSUE TITLE
Antispam Bee causes CLS (Cumulative Layout Shift)

### ISSUE THREAD

**Issue by AlessioGr** [pluginkollektiv/antispam-bee#385] opened 2021-04-12 15:50 UTC
Antispam Bee causes CLS issues on my website. Google PageSpeed results:

With Antispam Bee disabled: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgaming-lenkrad-experten.de%2Fps5-lenkrad%2F&tab=desktop
With Antispam Bee enabled: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgaming-lenkrad-experten.de%2Fps5-lenkrad%2F&tab=desktop

As you can see, once I enable Antispam Bee on my website, it introduces a CLS to 0.135 on the Desktop version. I ran these Google PageSpeed results multiple times to make sure it really is Antispam Bee causing it once it's enabled. I am getting the same results on GTMetrix as well.

This is another test where you can see the CLS: https://webvitals.dev/cls/LwI1TRwIbPpJyb5XhOwi

The CLS happens because the sidebar appears later than the main content, causing it to shift to the right. My website is using the GeneratePress Premium theme and is on the newest WordPress version.

I even managed to reproduce this issue with only Antispam Bee enabled and **all other plugins disabled (including GP Premium)**. This is the test result: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgaming-lenkrad-experten.de%2Fps5-lenkrad%2F&tab=desktop

It even happens after disabling all of my custom CSS: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgaming-lenkrad-experten.de%2Fps5-lenkrad%2F&tab=desktop

Although I didn't try it, you should probably be able to reproduce it on a fresh site - just make sure the sidebar is on the left side.

I re-enabled all plugins on my website again since it's a live site, but I left Antispam Bee installed for you to test these CLS issues.

**Comment by AlessioGr** [comment] 2021-04-12 15:52
I just noticed that clicking on the pagespeed links creates an entirely new pagespeed report. However, all the CLS scores on those results are the same (Cumulative Layout Shift 0.135 on Desktop). Only the first one without Antispam bee enabled has 0 CLS.

**Comment by Zodiac1978** [comment] 2021-04-12 19:19
`just make sure the sidebar is on the left side.`

I tried this on my testserver: Activated GeneratePress and set the layout to a left sidebar. Tested with and without ASB. And I always get a green CLS with a value from 0.001.

But there is an error in your console showing: `Uncaught ReferenceError: jQuery is not defined` - that maybe is interfering here.

https://webvitals.dev/cls/LwI1TRwIbPpJyb5XhOwi#desktop is showing the CLS as an animated layer. It is the main content shifting to the right. I have no idea why ASB should have anything to do with this layout change. As ware are just changing the comment form markup.

As I can't reproduce this at the moment I have just one explanation left. A mistake in the measuring. In the "Known Issues" of this CLS test it states two maybe relevant issues: 

* As these tests are made with headless browsers, maybe the (browser) cache is interfering here. (Maybe the results are cached itself?)
* Which brings me to the 0. If the test is failing, it defaults to zero. So is the 0 maybe just a test failing?

Did you try different orders of testing? Could you confirm that this CLS value is reproducible after enabling/disabling ASB?

Thanks for your help!

**Comment by AlessioGr** [comment] 2021-04-12 19:27
@Zodiac1978 

I've tried it multiple times, with 3 different testing tools: GTMetrix, pagespeed and webvitals.dev and got the same result.
I've tried different orders at different times of the day of having Antispam Bee enabled/disabled. Sometimes right after each other, sometimes after disabling the cache. The result was always the same. Disabling Antispam Bee fixed the issue every single time without an exception.

The CLS is also visible to visitors. A GeneratePress support team member told me that the CLS wasn't visible for him anymore after disabling the plugin.

I did disable jQuery on the frontend of my website, that's why I'm getting the console error.

Could you give me the WordPress login for your test server? Then I can try to reproduce it by setting everything up like it's set up on my live server. I currently don't have an own test server ready.

**Comment by Zodiac1978** [comment] 2021-04-12 22:36
@AlessioGr I will be not at my laptop tomorrow, so just a short heads up:

The CLS comes from `div#primary.content-area` which has nothing to do with ASB, like the support staff is saying in the last post here too:
https://generatepress.com/forums/topic/sidebar-causing-a-lot-of-cls-cumulative-layout-shift/#post-1730311

It looks like there is a small style.css loaded, then the browser renders the page and after that Autoptimize is loaded async and overwrites the styles which is causing the shift. So you should re-check your Autoptomize settings. Re-generating the critical path CSS there or in your theme (or whatever plugin is creating or messing around with it) may resolve your issue.
See: https://generatepress.com/forums/topic/high-cls-on-desktop-if-sidebar-is-enabled-0-01-when-sidebar-is-disabled/

Thanks to @Soean and Phil Marx for debugging help on Twitter! :)

**Comment by AlessioGr** [comment] 2021-04-12 23:41
@Zodiac1978 
I was surprised as well seeing Antispam Bee cause that issue. That's why I have disabled every single plugin apart from Antispam Bee and tested it out - with the same results. When Antispam Bee is enabled, I had these CLS issues. The moment I disabled it (so then I had 0 active plugins), the issue went away.

That's why I'm thinking it can't be a critical CSS issue/Autoptimize issue.

I'll set up a staging site tomorrow to try and reproduce this.

**Comment by AlessioGr** [comment] 2021-04-13 02:13
Antispam Bee on: https://gtmetrix.com/reports/mulan.templweb.com/rcHgwNlr/
Antispam Bee off: https://gtmetrix.com/reports/mulan.templweb.com/f18ERjBD/

I didn't reproduce the same effect (the layout shift doesn't disappear completely with Antispam Bee disabled), but it does get a much worse score.

Only plugins enabled were Antispam Bee and GeneratePress Premium. No additional CSS. You can access https://mulan.templweb.com/ps5-lenkrad/ using templ as both username and password. I'll send you the wp login details in a private message.

**Comment by Zodiac1978** [comment] 2021-04-14 09:46
@AlessioGr Thank you for the login credentials, but at the moment I just have the subscriber role and cannot see, test or change anything to further debug the issue. Can you give the profile the admin role, so that I can check more ideas?

**Comment by AlessioGr** [comment] 2021-04-14 14:37
> @AlessioGr Thank you for the login credentials, but at the moment I just have the subscriber role and cannot see, test or change anything to further debug the issue. Can you give the profile the admin role, so that I can check more ideas?

Oops, I forgot that. It has the admin role now!

**Comment by Zodiac1978** [comment] 2021-04-14 19:10
I am testing with Google Chrome in the Lighthouse tab locally and cannot reproduce these differences.

l always get green results for mobile and yellow results ("needs improvement") for desktop.

No different result if ASB is enabled or disabled.

**Comment by AlessioGr** [comment] 2021-04-17 14:28
> I am testing with Google Chrome in the Lighthouse tab locally and cannot reproduce these differences.
> 
> l always get green results for mobile and yellow results ("needs improvement") for desktop.
> 
> No different result if ASB is enabled or disabled.

The best way to test it seems to be GTMetrix. I cannot reproduce it locally as well - GeneratePress support told me that the reason for that might be my ISP cache. Also, the Lighthouse tab doesn't seem to be able to test it properly with that HTTP authentication.

GTMetric has an option where I can let it test with Authentification. I ran another test:
With Antispam Bee: https://gtmetrix.com/reports/mulan.templweb.com/7cicYb0b/ (0.16 CLS)
Without: https://gtmetrix.com/reports/mulan.templweb.com/GHevNTMa/ (0.05 CLS)

**Comment by marxphil** [comment] 2021-04-17 18:39
Could you please provide me the login credentials as well? I'd like to have a look into the site, so Torsten is not that alone ;)
Please use hallo@webfalken.de - thanks.

**Comment by AlessioGr** [comment] 2021-04-17 19:52
> [hallo@webfalken.de](mailto:hallo@webfalken.de)

Hey, I've sent you the details!

**Comment by marxphil** [comment] 2021-04-17 20:12
Thanks a lot.

Unfortunately I can' find a difference at all.
Disabled ASB: CLS 0.4
Activated ASB: CLS 0.4

Test parameter
![2021-04-17 22_10_34-Latest Performance Report for_ https___mulan templweb com_ _ GTmetrix - Persönli](https://user-images.githubusercontent.com/43323989/115125647-d1adc000-9fc9-11eb-88da-78d7bf848d00.png)

Even the scores are exactly the same. 
![ASB enabled](https://user-images.githubusercontent.com/43323989/115125602-8eebe800-9fc9-11eb-9c98-f4dbb470f84c.png)
![ASB disabled](https://user-images.githubusercontent.com/43323989/115125603-8f847e80-9fc9-11eb-87c9-036d35edba11.png)

For clarification:
I enabled ASB and did the check.
Afterwards I disabled the plugin and clicked "RE-Check".

How did you get to these different results?

**Comment by AlessioGr** [comment] 2021-04-17 22:22
@marxphil 
I just reproduced it again - this time using the same Vancouver test server you did. This is how:
(1) Enabled Antispam Bee
(2) Run test
(3) Run test again
Both tests gave me the same result (0.2 CLS): https://gtmetrix.com/reports/mulan.templweb.com/M3UmxO3a/
(4) Disable Antispam Bee
(5) Run test
(6) Run test again
Both tests gave me the same (better) result (0.05 CLS): https://gtmetrix.com/reports/mulan.templweb.com/Cj4u8N1a/

I've used these settings: 
![Screenshot 2021-04-18 001939](https://user-images.githubusercontent.com/70709113/115128138-edba5d00-9fdb-11eb-9094-ac8bd6166d97.png)


Maybe you ran the test using the wrong URL? I'm using https://mulan.templweb.com/ps5-lenkrad/

There hasn't been a single case where I could not reproduce it.

**Comment by stklcode** [comment] 2021-04-18 06:33
I do experience a visible layout shift with ASB disabled (I guess, fresh test yields 0.05). Same in mobile and desktop Chrome.

So I would fix the general CLS first place and then re-evaluate ASB impact again.

My guess would be that ASB is causing just enough slow-down in the critical execution path that the time gap increases to impact the score. However an A-rating is one thine, real-life UX another. And the latter is not different at all, here.

**Comment by AlessioGr** [comment] 2021-04-18 14:43
> I do experience a visible layout shift with ASB disabled (I guess, fresh test yields 0.05). Same in mobile (stronger) and desktop Chrome.
> 
> So I would fix the general CLS first place and then re-evaluate ASB impact again.
> 
> My guess would be that ASB is causing just enough slow-down in the critical execution path that the time gap increases to impact the score (no detailed analysis). However an A-rating is one thing, real-life UX another. And the latter is not different at all, here.

On my main website, I did fix the CLS by either replacing ASB **or** moving the sidebar to the right side. Disabling it did get the CLS to 0, and it wasn't noticeable anymore. I'll create another staging site with the full version of my website, where you can see that.

**Comment by AlessioGr** [comment] 2021-04-18 16:03
@stklcode 
The new staging site is ready. Password, URL and username are the same.

This is without AntiSpam Bee enabled: https://gtmetrix.com/reports/mulan.templweb.com/9KwZJThx/
And this is with AntiSpam Bee enabled: https://gtmetrix.com/reports/mulan.templweb.com/xMixSUKp/

I've enabled the GTMetrix Video feature for those two records, so you can actually see the layout shift. The problematic element is `<div id="primary" class="content-area">`

**Comment by Zodiac1978** [comment] 2021-08-12 09:45
I think after the examinations here there is no bug in ASB. I think @stklcode is right with his comment:
> My guess would be that ASB is causing just enough slow-down in the critical execution path that the time gap increases to impact the score

Therefore I don't see a possibility or need to fix anything in ASB. Maybe this is fixed by our different approach (ob_* vs. filter) in 2.10.0 already.

I close this issue for now. If new insights are coming up, please open again with more details and we have a second look!

**Closed by Zodiac1978** 2021-08-12 09:45 UTC
